#!/bin/bash
BRANCH=`git branch --show-current`
REPO_DIR=`git rev-parse --show-toplevel`
REPO=`basename $REPO_DIR`
if [ $BRANCH = "main" ]; then BRANCH="latest"; fi
docker build . -t ghcr.io/ptr33/$REPO:$BRANCH   && \
docker push ghcr.io/ptr33/$REPO:$BRANCH
